### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by VishalSharma2000**
Update Readme file to add description about which node version to use before running `npm install`.

### CODE REVIEW

**Comment by VishalSharma2000** [comment]
During local setup I mistakenly ran `npm install` before changing the version of node. The default version of node was not v18. 

I ran into some warnings, stating `Unsupported engines`.

So, thought of specifying it explicitly so that other people change the node version before downloading the dependencies.

Please let me know your views and any changes required in the added documentation.

**Comment by miroslavpejic85** [comment]
LGTM, 

Can you please change the comment in 

The project was tested with node version 18.16.0 ...

Thank you.

**Comment by VishalSharma2000** [comment]
Sorry @miroslavpejic85, didn't got you.

Are you asking me to update the `The project requires node version = 18.16.0` in the added line to update to `The project was tested with node version 18.16.0`?

**Comment by miroslavpejic85** [comment]
Exactly! The other part of the comment is ok ;)

```bash
# The project was tested with node version 18.16.0. So make sure to update the node version using nvm if you have multiple version installed.
# After updating the node version, you can verify using
$ node --version # v18.16.0
...
```

**Comment by VishalSharma2000** [comment]
Updated.

Please let me know if you feel any more changes can be made :)

**Pull request merged**
