### PR TITLE
Issue#4_resolved

### PR DESCRIPTION
**Pull request by Shivansh175**
I've done the required changes. Please check it out and merge this pr by adding the hacktoberfest accepted tag :)

### CODE REVIEW

**Comment by miroslavpejic85** [comment]
> I've done the required changes. Please check it out and merge this pr by adding the hacktoberfest accepted tag :)
ignore

Please, delete then add the `.vscode` directory in [.gitignore](https://github.com/miroslavpejic85/mirotalkwebrtc/blob/master/.gitignore) file to exclude it from being tracked by Git. 
```bash
# VSCode settings
.vscode/
```

Thank you.

**Comment by Shivansh175** [comment]
ain't your project not taking part in hactoberfest anymore??
Screenshot 2023-10-05 222020

**Comment by miroslavpejic85** [comment]
> ain't your project not taking part in hactoberfest anymore?? Screenshot 2023-10-05 222020

Added topic: `hacktoberfest` right now, you see the same message?

**Comment by Shivansh175** [comment]
yeah it is still same

**Comment by miroslavpejic85** [comment]
I added also the `label`: `hacktoberfest-accepted`
PS: please remove `migrate-mongo-config.js` in `.gitignore` Not mine file...
Thank you.

**Comment by Shivansh175** [comment]
please clarify do i have to remove this file named 'migrate-mongo-config.js' or just have to remove the line 'migrate-mongo-config.js' from gitignore file...
Sorry for these silly questions...i'm very new to these complex codebases and folder structures 🥲so please help

**Comment by miroslavpejic85** [comment]
> migrate-mongo-config.js

A no, sorry, It's ok! You not need to do nothing ;) 
At the end I did the task for you lol 🥇

**Comment by Shivansh175** [comment]
:_) thnx

**Comment by miroslavpejic85** [comment]
> :_) thnx

`Merged`: Don't fret, you'll keep improving! Thanks a bunch for spending time with me! 🌟

**Comment by Shivansh175** [comment]
✨🫡

**Pull request merged**
